In [1]:
import numpy as np

In [2]:
x = np.array([1])

In [3]:
x

array([1])

In [4]:
x.shape

(1,)

In [5]:
x = np.random.random((1))

In [6]:
x

array([0.90570605])

---

In [35]:
shape = (2)

In [36]:
x = np.random.randint(0,10,shape)

In [37]:
x

array([3, 7])

---

In [32]:
shape = (2,2)

In [33]:
x = np.random.randint(0,10,shape)

In [34]:
x

array([[2, 6],
       [7, 1]])

---

In [38]:
shape = (2,2,2)

In [39]:
x = np.random.randint(0,10,shape)

In [40]:
x

array([[[0, 3],
        [4, 9]],

       [[9, 0],
        [0, 8]]])

---

In [29]:
shape = (2,2,2,2)

In [30]:
x = np.random.randint(0,10,shape)

In [31]:
x

array([[[[0, 5],
         [4, 2]],

        [[6, 0],
         [5, 1]]],


       [[[3, 4],
         [7, 8]],

        [[3, 0],
         [8, 4]]]])

---

In [64]:
x = np.random.randint(0,10,[2,1])
y = np.random.randint(0,10, [1,2])

In [65]:
x

array([[0],
       [2]])

In [66]:
y

array([[4, 4]])

In [67]:
x.dot(y)

array([[0, 0],
       [8, 8]])

In [68]:
y.dot(x)

array([[8]])

---

In [1]:
import tensorflow as tf

In [66]:
tf.reset_default_graph()

In [67]:
shape = [5, 30]
value = tf.Variable(tf.random_normal(shape, stddev=0.01))

In [68]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    #print(value.eval())
    #print(tf.shape(value))
    print(value.shape)
    # 'value' is a tensor with shape [5, 30]
    # Split 'value' into 3 tensors with sizes [4, 15, 11] along dimension 1
    split0, split1, split2 = tf.split(value, [4, 15, 11], 1)
    print(tf.shape(split0).eval())  # [5, 4]
    #print(split0.shape)
    print(tf.shape(split1).eval())  # [5, 15]
    #print(split1.shape)
    print(tf.shape(split2).eval())  # [5, 11]
    #print(split2.shape)
    # Split 'value' into 3 tensors along dimension 1
    split0, split1, split2 = tf.split(value, num_or_size_splits=3, axis=1)
    print(tf.shape(split0).eval())  # [5, 10]

(5, 30)
[5 4]
[ 5 15]
[ 5 11]
[ 5 10]
