Some simple exercise after encountering 'reduce_max' in GPT-2, cf. [this video](https://www.aiworkbox.com/lessons/calculate-max-of-a-tensor-along-an-axis-using-tensorflow).

The [TF reference](https://www.tensorflow.org/api_docs/python/tf/math/reduce_max).

In [1]:
import tensorflow as tf

In [2]:
tf.enable_eager_execution()

In [3]:
rand = tf.get_variable("rand",
                      initializer=tf.random_uniform([2,3,4],
                                                   minval=0,
                                                   maxval=20,
                                                   dtype=tf.int32))

In [4]:
rand

<tf.Variable 'rand:0' shape=(2, 3, 4) dtype=int32, numpy=
array([[[15, 14,  1,  5],
        [19,  1,  0,  1],
        [ 0, 18,  9,  0]],

       [[10, 19, 18, 18],
        [17, 16,  5,  3],
        [ 9, 18, 11, 13]]], dtype=int32)>

In [12]:
# without argument, we simply get the max integer
tf.reduce_max(rand)

<tf.Tensor: id=46, shape=(), dtype=int32, numpy=19>

In [17]:
# compares the two 3x4 matrices pointwise, keeps the max element
tf.reduce_max(rand, axis=[0])

<tf.Tensor: id=74, shape=(3, 4), dtype=int32, numpy=
array([[15, 19, 18, 18],
       [19, 16,  5,  3],
       [ 9, 18, 11, 13]], dtype=int32)>

In [7]:
# compares each 3x4 matrix 'internally'/'columnwise' (squish rows, taking the max of each column)
tf.reduce_max(rand, axis=[1])

<tf.Tensor: id=20, shape=(2, 4), dtype=int32, numpy=
array([[19, 18,  9,  5],
       [17, 19, 18, 18]], dtype=int32)>

In [9]:
# compares each 3x4 matrix 'internally'/'rowwise' (squish columns, taking the max of each row)
tf.reduce_max(rand,axis=[2])

<tf.Tensor: id=28, shape=(2, 3), dtype=int32, numpy=
array([[15, 19, 18],
       [19, 17, 18]], dtype=int32)>

---

In [10]:
rand

<tf.Variable 'rand:0' shape=(2, 3, 4) dtype=int32, numpy=
array([[[15, 14,  1,  5],
        [19,  1,  0,  1],
        [ 0, 18,  9,  0]],

       [[10, 19, 18, 18],
        [17, 16,  5,  3],
        [ 9, 18, 11, 13]]], dtype=int32)>

In [14]:
# keepdims keeps the dims
tf.reduce_max(rand, keepdims=True)

<tf.Tensor: id=62, shape=(1, 1, 1), dtype=int32, numpy=array([[[19]]], dtype=int32)>

In [18]:
tf.reduce_max(rand,
              axis=[2],
              keepdims=True)

<tf.Tensor: id=78, shape=(2, 3, 1), dtype=int32, numpy=
array([[[15],
        [19],
        [18]],

       [[19],
        [17],
        [18]]], dtype=int32)>