# PyTorch

The [60 minutes blitz](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py)

In [1]:
import torch

In [2]:
x = torch.empty(5,3)
print(x)

tensor([[1.3452e-43, 0.0000e+00, 0.0000e+00],
        [9.2196e-41, 0.0000e+00, 0.0000e+00],
        [1.3695e+18, 4.5879e-41, 1.6817e+19],
        [4.5879e-41, 1.4013e-45, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 7.0017e+19]])


In [7]:
x = torch.rand(5,3)
print(x)
print()
print(x*10) # broadcasting

tensor([[0.7991, 0.9557, 0.0134],
        [0.7330, 0.1730, 0.6028],
        [0.3702, 0.3724, 0.2919],
        [0.8797, 0.2601, 0.5675],
        [0.6395, 0.3591, 0.3447]])

tensor([[7.9908, 9.5572, 0.1335],
        [7.3299, 1.7302, 6.0277],
        [3.7015, 3.7243, 2.9194],
        [8.7967, 2.6013, 5.6753],
        [6.3950, 3.5911, 3.4466]])


In [10]:
x = torch.zeros(5,3, dtype=torch.long)
print(x)
print()
x = torch.zeros(5,3, dtype=torch.int)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)


In [12]:
x = torch.tensor([12,4,5], dtype=torch.float)
print(x)

tensor([12.,  4.,  5.])


In [13]:
x = x.new_ones(5,3, dtype=torch.double)
print(x)
print()
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

tensor([[-0.6746, -0.3375, -1.8664],
        [ 0.6490,  1.1153, -0.1087],
        [ 0.4288, -1.7052, -0.3766],
        [ 0.1721, -0.4489, -1.2904],
        [-1.4313, -0.9476, -0.0326]])


In [15]:
print(x.size())
# it is a tuple:
a, b = x.size()
print(a, b)

torch.Size([5, 3])
5 3


In [17]:
print(x)
print()
y = torch.rand(5,3)
print(y)
print()
print(x + y)

tensor([[-0.6746, -0.3375, -1.8664],
        [ 0.6490,  1.1153, -0.1087],
        [ 0.4288, -1.7052, -0.3766],
        [ 0.1721, -0.4489, -1.2904],
        [-1.4313, -0.9476, -0.0326]])

tensor([[0.0089, 0.0303, 0.1899],
        [0.4879, 0.6921, 0.2623],
        [0.0102, 0.1642, 0.5201],
        [0.3382, 0.1860, 0.8925],
        [0.9644, 0.0805, 0.5989]])

tensor([[-0.6658, -0.3073, -1.6765],
        [ 1.1369,  1.8074,  0.1536],
        [ 0.4390, -1.5410,  0.1436],
        [ 0.5103, -0.2629, -0.3979],
        [-0.4669, -0.8671,  0.5662]])


In [18]:
print(torch.add(x,y))

tensor([[-0.6658, -0.3073, -1.6765],
        [ 1.1369,  1.8074,  0.1536],
        [ 0.4390, -1.5410,  0.1436],
        [ 0.5103, -0.2629, -0.3979],
        [-0.4669, -0.8671,  0.5662]])


In [19]:
result = torch.empty(5,3)
print(result)
print()
torch.add(x, y, out=result)
print(result)

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 1.3593e-43, 0.0000e+00],
        [1.1816e+13, 3.0681e-41, 1.1673e+13]])

tensor([[-0.6658, -0.3073, -1.6765],
        [ 1.1369,  1.8074,  0.1536],
        [ 0.4390, -1.5410,  0.1436],
        [ 0.5103, -0.2629, -0.3979],
        [-0.4669, -0.8671,  0.5662]])


all methods ending with '_' act in place...

In [20]:
print(y)
print()
y.add_(x)
print(y)

tensor([[0.0089, 0.0303, 0.1899],
        [0.4879, 0.6921, 0.2623],
        [0.0102, 0.1642, 0.5201],
        [0.3382, 0.1860, 0.8925],
        [0.9644, 0.0805, 0.5989]])

tensor([[-0.6658, -0.3073, -1.6765],
        [ 1.1369,  1.8074,  0.1536],
        [ 0.4390, -1.5410,  0.1436],
        [ 0.5103, -0.2629, -0.3979],
        [-0.4669, -0.8671,  0.5662]])


In [26]:
x.mul_(10)
print(x)
print()
print(x[:,1]) # second number of each vector
print()
print(x[0,0])
print()
print(x[-1,:-1]) # last vector, everything but the last element

tensor([[ -6.7463,  -3.3754, -18.6641],
        [  6.4903,  11.1530,  -1.0870],
        [  4.2880, -17.0521,  -3.7656],
        [  1.7210,  -4.4890, -12.9040],
        [-14.3126,  -9.4760,  -0.3263]])

tensor([ -3.3754,  11.1530, -17.0521,  -4.4890,  -9.4760])

tensor(-6.7463)

tensor([-14.3126,  -9.4760])


In [27]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [28]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.2028])
0.20284658670425415


In [30]:
a = torch.ones(2,3,4)
print(a)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


In [35]:
b = a.numpy()
print(b)
print()
print(type(b))

[[[2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]]

 [[2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]]]

<class 'numpy.ndarray'>


In [34]:
a.add_(1)
print(a)
print()
print(b)

tensor([[[2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.]],

        [[2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.]]])

[[[2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]]

 [[2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]]]


In [36]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print()
print(b)

[2. 2. 2. 2. 2.]

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [37]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print()
    print(z.to("cpu", torch.double))

---

# Autograd

In [44]:
a = torch.randn(2, 2) # drawn from a normal distribution with mean 0 and stddev 1
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True) # change flag in-place
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


---
A series of operations:

In [39]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [40]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [41]:
print(y.grad_fn)

In [43]:
z = y * y * 3
out = z.mean()

print(z)
print()
print(out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)

tensor(27., grad_fn=<MeanBackward0>)


In [45]:
out.backward() # same as out.backward(torch.tensor(1.)), as out is a scalar

In [46]:
print(x.grad) # the Jacobian matrix

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


The operations (from the documentation):

$ out = \frac{1}{4}\sum_{i}z_i$  

$ z_i = 3\left(x_i + 2\right)^2$

$ z_i\bigr\rvert_{x_i=1} = 27 $  

$ \frac{\partial o}{\partial x_i} = \frac{3}{2}\left(x_i+2\right) $

$ \frac{\partial o}{\partial x_i}\bigr\rvert_{x_i=1} = \frac{9}{2} = 4.5 $

#### Mathematically, given a vector-valued function $ \vec{y}=f(\vec{x}) $, the gradient of $ \vec{y} $ with respect to $ \vec{x} $ is a Jacobian matrix: $
  J=\left(\begin{array}{ccc}
   \frac{\partial y_{1}}{\partial x_{1}} & \cdots & \frac{\partial y_{1}}{\partial x_{n}}\\
   \vdots & \ddots & \vdots\\
   \frac{\partial y_{m}}{\partial x_{1}} & \cdots & \frac{\partial y_{m}}{\partial x_{n}}
   \end{array}\right) $

Generally speaking, ``torch.autograd`` is an engine for computing vector-Jacobian product. That is, given any vector 
$ v=\left(\begin{array}{cccc} v_{1} & v_{2} & \cdots & v_{m}\end{array}\right)^{T} $
, compute the product 
$ v^{T}\cdot J  $
. If $ v $ happens to be the gradient of a scalar function 
$ l=g\left(\vec{y}\right) $
, that is, 
$ v=\left(\begin{array}{ccc}\frac{\partial l}{\partial y_{1}} & \cdots & \frac{\partial l}{\partial y_{m}}\end{array}\right)^{T} $
, then by the chain rule, the vector-Jacobian product would be the gradient of $ l $ with respect to $ \vec{x} $ :

$
  J^{T}\cdot v=\left(\begin{array}{ccc}
   \frac{\partial y_{1}}{\partial x_{1}} & \cdots & \frac{\partial y_{m}}{\partial x_{1}}\\
   \vdots & \ddots & \vdots\\
   \frac{\partial y_{1}}{\partial x_{n}} & \cdots & \frac{\partial y_{m}}{\partial x_{n}}
   \end{array}\right)\left(\begin{array}{c}
   \frac{\partial l}{\partial y_{1}}\\
   \vdots\\
   \frac{\partial l}{\partial y_{m}}
   \end{array}\right)=\left(\begin{array}{c}
   \frac{\partial l}{\partial x_{1}}\\
   \vdots\\
   \frac{\partial l}{\partial x_{n}}
   \end{array}\right)
$

(Note that $ v^{T}\cdot J $  gives a row vector which can be treated as a column vector by taking $ J^{T}\cdot v $ .)

---

In [47]:
x = torch.randn(3, requires_grad=True)
y = x * 2
while y.data.norm() < 1000:
    y = y*2
print(y)

tensor([-513.9047,  657.9506, -858.0045], grad_fn=<MulBackward0>)


In [48]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)
print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


In [49]:
print(x.requires_grad)
print((x ** 2).requires_grad)
with torch.no_grad():
    print((x**2).requires_grad)

True
True
False


---

# Network

From the tutorial, typical procedure:
- define the neural network with some learnable parameters (or weights)
- iterate over the dataset of inputs
- process input through the network
- compute the loss (how correct the network's predictions are)
- propagate gradients back into the network's parameters
- update the weights of the network, using a simple rule `weight = weight - learning_rate * gradient`

In [51]:
import torch.nn as nn
import torch.nn.functional as F